config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'static#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
 
  resources :users

  resources :categories, only: [:new, :index, :create]
  resources :comments
  
  resources :workouts do
    resources :comments, only: [:new, :index]
  end

end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user 
    belongs_to :category

    has_many :comments
    has_many :users, through: :comments

    validates :title, presence: true
    validates :description, presence: true
    validates :time, presence: true
    validates :difficulty, presence: true
    validate :already_exists
    


    #scope methods
    scope :order_by_comments, -> { left_joins(:comments).group(:id).order("size desc")}

    def self.filter_by_title(value)
      where("title like ?" , "%#{value}%")
    end

     
    def self.order_by_difficulty
      order(difficulty: :desc)
    end   

    def self.order_by_size
      order(comments: :desc)
    end   

    def self.by_user(user_id)
      where(user: user_id)
    end

    def self.today
      where("created_at >=?", Time.zone.today.beginning_of_day)
    end
     
    def self.past
      where("created_at <?", Time.zone.today.beginning_of_day)
    end








    def already_exists
        workout = Workout.find_by(title: title, category_id: category_id)
    if !!workout && workout != self
      errors.add(:title, 'has already been added for that category')
    end
    end



    def title_category
     "#{title} - #{category.name}"
    end


    def category_attributes=(hash)
      category = Category.find_or_create_by(name: hash[:name])
      #push it into workout
      self.category = category
    end


   
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :require_login
    before_action :set_workout, only: [:edit, :update, :show, :destroy]
    

    def index
        if params["/workouts"]
        @workouts = Workout.all
        @workouts = Workout.filter_by_title(params["/workouts"][:title])
        else
        @workouts = Workout.all


        if !params[:user].blank?
            @workouts.order_by_size
        elsif !params[:date].blank?
            if params[:date] == "Today"
              @workouts = Workout.today
            else
              @workouts = Workout.past
            end
        else   # if no filters are applied, show all workouts by most comments
            @workouts.order_by_comments
        end
   
    end
    end

    
    def new
        @workout = Workout.new     
        @workout.build_category
    end

    def create 
        @workout = Workout.new(workout_params)
        @workout.user_id = session[:user_id]
            if @workout.save
                redirect_to workout_path(@workout)
            else
                render :new
            end
    end

    def show
        @comments = @workout.comments
    end

    def edit
        if session[:user_id] != @workout.user_id
            redirect_to user_path(session[:user_id])
        end 
    end

    def update
            if @workout.update(workout_params)
                redirect_to workouts_path
            else
                render :edit
            end
    end

    def destroy 
        if current_user_check != @workout.user_id
            redirect_to user_path(session[:user_id])
        else 
            @workout.destroy
            redirect_to workouts_path
        end
    end

    private


    def workout_params
        params.require(:workout).permit(:title, :description, :time, :difficulty, category_attributes: [:name])
    end

    def set_workout
        @workout = Workout.find_by(id: params[:id])
    end


end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_filter.html.erb
                        <div>
                          <h3>Filter posts:</h3>
                          <%= form_tag("/workouts", method: "get") do %>
                            <%= select_tag "date", options_for_select(["Today", "Past"]), include_blank: true %>
                            <%= submit_tag "Filter" %>
                          <% end %>
                        </div>

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>

    <div>
        <%= f.label :time %>
        <%= f.number_field :time, min: 1, max: 120 %>
    </div>

    <div>
        <%= f.label :difficulty %>
        <%= f.number_field :difficulty, min: 1, max: 5 %>
    </div>

    <p>Add A Category:</p>
    <div>
        <%= f.fields_for :category do |m| %>
            <%= m.label :name %>
            <%= m.text_field :name %>
        <datalist id="category_name">
            <% Category.all.each do |c| %>
           <option value = "<%= c.name %>"  ></option>
            <% end %>
        </datalist>
        <br>
        <% end %>
    </div>
        <%= f. submit %>
<% end %>




 

app/views/workouts/_style.html.erb
<style>
 #cover {
    background: #222 url('https://source.unsplash.com/1600x900/?fitness,people') center center no-repeat;
    background-size: cover;
    height: 100%;
    text-align: center;
    display: flex;
    align-items: center;
    position: relative;
    color: teal;
}

#cover-caption {
    width: 100%;
    position: relative;
    z-index: 1;
}

/* only used for background overlay not needed for centering */
form:before {
    content: '';
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100%;
    background-color: rgba(0,0,0,0.7);
    z-index: -1;
    border-radius: 10px;
}

.blk_center {

    width: 100%;
    background-color: rgba(0,0,0,0.6);
    z-index: -1;
    border-radius: 20px;
    display:inline-block;
}

</style>

app/views/workouts/edit.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                    <h1 class="display-4 py-2 text-truncate text-primary">Edit Workout</h1>
                        <div class="px-2">

                        <%= render 'form' %>

                
                    </div>
                </div>
            
        </div>
    </div> 
</section>


<%= render 'style' %>

app/views/workouts/index.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form h5-4">
                        <div class="px-2 ">
                          <br>
                          <div class="card text-white bg-dark mb-3">  

                          <%= render 'filter' %>

                          <%= form_for(workouts_path, method: :get) do |f| %>
                          <%= f.label :title %>
                          <%= f.search_field (:title) %>
                          <%= f.submit "Submit" %>
                          <% end %>

                            <h3>All of the workouts!</h3>
                          </div>
                          <hr>
                            <% @workouts.each do |w| %>
                            <div class="blk_center row card-deck border-info mb-3">
                            <h3>Name - <%= w.user.username %></h3>
                            <%= check_image(w.user) %>

                            <h5>Title of workout - <%= w.title %></h5>
                            <h5>Description of workout -  <%= w.description %> </h5>
                            <h5>Time of Workout -  <%= w.time %> Minutes</h5>
                            <h5>Difficulty - <%= w.difficulty %>  </h5>
                            <h5>Comments - <%= w.comments.count %>  </h5>
                            <h5>Category - <%= w.category.name %>
                            <br>
                            <%= link_to "Show workout", workout_path(w.id) %>
                            <br>
                            <%= link_to "Edit workout", edit_workout_path(w.id) if w.user_id == session[:user_id] %>
                            <br>
                            <%= link_to "Delete workout", workout_path(w), :confirm => "Are you sure?", :method => :delete if w.user_id == session[:user_id] %>
                            <br>
                            <%= link_to "Add a comment", new_workout_comment_path(w.id) %>
                            </div>
                            <hr>
                            <% end %>
                        

                </div>
                
                
        </div> 
      </div>
</section>



<%= render 'style' %>

app/views/workouts/new.html.erb
<%= render partial: 'layouts/errors', locals: {obj: @workout} %>

<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                    <h1 class="display-4 py-2 text-truncate text-primary">Add Workout</h1>
                        <div class="px-2">
                        
                        <%= render 'form' %>
                        <%= link_to  "Cancel", user_path(session[:user_id]) %>

                
                    </div>
                </div>
            
        </div>
    </div> 
</section>
<%= render 'style' %>


 

app/views/workouts/show.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">

                            <h1>Show Workout Page</h1>
                            <div class="blk_center row card-deck border-info text-white mb-3">
                            <h3><%= check_image(@workout.user) %><%= @workout.user.username %></h3>

                            <h3>Title of workout - <%= @workout.title %></h3>
                            <p>Description of workout -  <%= @workout.description %> </p>
                            <p>Time of Workout -  <%= @workout.time %> Minutes</p>
                            <h3>Difficulty - <%= @workout.difficulty %>  </h3>
                            </div>
                            <br>
                            <div class="blk_center row card-deck border-primary mb-3 text-warning">
                            <% @comments.all.each do |c| %>
                                <%= check_image(c.user) %> 
                                <h5 class="text-info"><%= c.user.username.capitalize %> posted</h5>
                                <h5>Title - <%= c.title %></h5>
                                <h5> Created-at <%= c.created_at %></h5>
                                <hr>
                                <% end %> 
                                <%= link_to  "View Comments", workout_comments_path(@workout) %>
                            </div>
                </div>
            
        </div>
    </div> 
</section>

<%= render 'style' %>