config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'static#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
 
  resources :users

  resources :categories, only: [:new, :index, :create]
  resources :comments
  
  resources :workouts do
    resources :comments, only: [:new, :index]
  end

end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
    has_many :workouts, through: :comments

    has_many :workouts #created workouts
    
    validates :username, uniqueness: true, presence: true, length: { minimum: 5}
    validates :email, uniqueness: true, presence: true
    validates :password, length: { in: 6..100 }
    
    has_secure_password

    has_one_attached :image

    

    def self.create_google_omniauth(auth)
        self.find_or_create_by(email: auth[:info][:email]) do |u|
            
            u.username = auth["info"]["name"]
            u.password = SecureRandom.hex
    
        end  
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new
        @user = User.new
    end

    def index
        @users = User.all
    end

    def create
        @user = User.new(user_params)
        if @user.save
            create_session
            redirect_to user_path(@user)
        else
            render :new
        end
    end


    def show
        @user = User.find_by(id: params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :image)
    end

    
end

app/helpers/users_helper.rb
module UsersHelper

    def check_image(user)
        image_tag (user.image), size: "100x80" unless user.image.attachment == nil 
    end

    
end

app/views/users/_form.html.erb
<%= simple_form_for @user,
    wrapper_mappings: {
    boolean:       :custom_boolean,
    check_boxes:   :custom_collection,
    date:          :custom_multi_select,
    datetime:      :custom_multi_select,
    file:          :custom_file,
    radio_buttons: :custom_collection,
    range:         :custom_range,
    time:          :custom_multi_select,
    select:        :custom_multi_select
    } do |f| %>
    
<%= f.error_notification %>
<div class="form-group text-primary h5">
    <%= f.input :username %>
</div>
<div class="form-group text-primary h5">
    <%= f.input :email %>
</div>
<div class="form-group text-primary h5">
    <%= f.input :password %>
</div>
<div class="form-group text-primary h5">
    <%= f.file_field :image %>
</div>
<div class="form-group text-primary h5">
    <%= f.button :submit, class: "btn-primary" %>
    <%= link_to "Cancel", "/", class: "btn btn-danger" %>
    
</div>
<% end %>

app/views/users/_workouts.html.erb
<% @user.workouts.each do |w| %>
    <div class="blk_center text-light">
        <h4>Title - <%= w.title %><br></h4>
        <h4>Description -<%= w.description %><br>
        <h4>Time -<%= w.time %> Minutes<br>
        <h4>Difficulty -<%= w.difficulty %><br>
    <%= link_to "Show workout/Comments", workout_path(w.id) %>
    <br>
    <%= link_to "Edit workout", edit_workout_path(w.id) if w.user_id == session[:user_id] %>
    <br>
    <%= link_to "Delete workout", workout_path(w), :confirm => "Are you sure?", :method => :delete if w.user_id == session[:user_id] %>
    <br>
    <%= link_to "Add a comment", new_workout_comment_path(w.id) %>
    </div>
        <hr>
<% end %>

app/views/users/index.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                    <%= image_tag("Main_logo.png", size: "300x50") %> 
                    <div class="px-2">


                            <% @users.each do |u| %>
                            <div class="blk_center row card-deck border-info mb-3">
                            <h3><%= check_image(u)%> User - <%= u.username %></h3>
                            <h5>Created on - <%= u.created_at %><h5>
                            </div>
                            
                            <% end %>



                </div>
            </div>
        </div>
    </div>
</section>

<%= render 'workouts/style' %>

app/views/users/new.html.erb


<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                    <h1 class="display-4 py-2 text-truncate text-primary">Sign Up</h1>
                    <%= image_tag("Main_logo.png", size: "300x50") %> 
                    <div class="px-2">

                      <%= render 'form' %>

                      </div>
        </div>
    </div>
    </div>
</section>


<%= render 'workouts/style' %>

app/views/users/show.html.erb
<section id="cover" class="min-vh-100">
    <div id="cover-caption">
        <div class="container">
                <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4">
                    <%= image_tag("Main_logo.png", size: "300x50") %> 
                    <div class="px-2">

                        <h1>Welcome <div class="text-success"><%= @user.username %></div></h1>
                        
                        <%= check_image(@user) %> 
                        

                            <h1>Your workouts</h1>
                            
                            <%= render 'workouts' %>

                </div>
            </div>
        </div>
    </div>
</section>

<%= render 'workouts/style' %>