config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'static#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
 
  resources :users

  resources :categories, only: [:new, :index, :create]
  resources :comments
  
  resources :workouts do
    resources :comments, only: [:new, :index]
  end

end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(obj.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
        <li class="nav-item">
          <a class="nav-link" <%= link_to  "Your Homepage", user_path(session[:user_id]) %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to  "New Workout", new_workout_path %> </a>
        </li>
        <li class="nav-item">
           <a class="nav-link" <%= link_to  "All Workouts", workouts_path %> </a>
        </li>
        <li class="nav-item">
           <a class="nav-link" <%= link_to  "All Categories", categories_path %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to  "Log Out", logout_path, method: :delete %> </a>
        </li>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialFitness</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.5.1.slim.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"  %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" %>

    <link rel="apple-touch-icon" sizes="180x180" href="./assets/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./assets/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="./assets/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    

  </head>

  <body>
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
  <div class="container">
    <a class="navbar-brand" href="/">Social Fitness</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home
                <span class="sr-only">(current)</span>
              </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to  "All Users", users_path %> </a>
        </li>


    <% if logged_in? %>

        <%= render 'layouts/nav' %>
        
    <% end %>
    
      </ul>
    </div>
  </div>

</nav>
</header>







    <%= yield %>
 



  </body>
</html>